### ISSUE TITLE
deploy new versions to chrome web store

### ISSUE THREAD

**Issue by aisbergde** [enrico-kaack/markdown-clipper#14]
it looks like the project has some commits, but the version in chrome web store
https://chrome.google.com/webstore/detail/markdown-clipper/cjedbglnccaioiolemnfhjncicchinao
is from 2019-01-07

**Comment by enrico-kaack** [comment]
Hi, the new version is submitted to both Firefox Add On Store and Chrome Webstore. It will be available after review.
