### ISSUE TITLE
Libraries used

### ISSUE THREAD

**Issue by Dudaevskiy** [enrico-kaack/markdown-clipper#6]
I am very interested in knowing which library is used to process HTML?
It works out well, but at the moment there are serious problems with tables, code, and iframes.

**Comment by atreya2011** [comment]
Readability.js 

https://github.com/mozilla/readability

**Comment by enrico-kaack** [comment]
If you find problems with tables, codes and iframe, please check if it works with the readability mode in Firefox. Like atreya2011 pointed out, it uses the library readability, which is the same like the Firefox readability mode. So if it doesn't work correctly in the Firefox mode, please open an issue at https://github.com/mozilla/readability .
